resource "google_compute_instance_template" "instance_template" {
  // ...
  network_interface {
    network = google_compute_network.gcp_vpc_network.self_link
    // ...
  }
  // ...
}

resource "google_compute_firewall" "firewall" {
  // ...
  network = google_compute_network.gcp_vpc_network.self_link
  // ...
}